/** backend 인증·계정 오류 코드의 사용자 중립 정본. */
export const AuthErrorCode = {
  ACCESS_TOKEN_REQUIRED: 'AUTH_001', ACCESS_TOKEN_EXPIRED: 'AUTH_002', ACCESS_TOKEN_INVALID: 'AUTH_003',
  TOKEN_NAMESPACE_MISMATCH: 'AUTH_004', INVALID_CREDENTIALS: 'AUTH_005', FORBIDDEN: 'AUTH_006',
  REFRESH_TOKEN_REQUIRED: 'AUTH_007', REFRESH_TOKEN_INVALID: 'AUTH_008', CSRF_TOKEN_INVALID: 'AUTH_009',
  ORIGIN_REJECTED: 'AUTH_010', ACCOUNT_RESTRICTED: 'AUTH_011', INITIAL_PASSWORD_CHANGE_REQUIRED: 'AUTH_012',
  KAKAO_OAUTH_INVALID: 'AUTH_013', KAKAO_ALREADY_LINKED: 'AUTH_014', PLATFORM_OPERATOR_SESSION_INVALID: 'AUTH_015',
  MEMBER_SUPPORT_NOT_FOUND: 'AUTH_018', MEMBER_SUPPORT_STATE_CONFLICT: 'AUTH_019',
  PERMANENT_SANCTION_APPROVAL_CONFLICT: 'AUTH_020',
} as const
export const AccountErrorCode = {
  EMAIL_ALREADY_EXISTS: 'ACCOUNT_001', PHONE_ALREADY_EXISTS: 'ACCOUNT_002',
  NICKNAME_CHANGE_TOO_SOON: 'ACCOUNT_005', RESERVATION_CONTACT_REQUIRED: 'ACCOUNT_006',
  CONTACT_CHANGE_NOT_ALLOWED: 'ACCOUNT_007',
} as const
export function isRefreshableAuthError(code: string): boolean {
  return code === AuthErrorCode.ACCESS_TOKEN_EXPIRED
}
