package com.miriyum.domain.menu.enums;

public enum MenuPublicationEventType {
    DRAFT_CREATED,
    DRAFT_UPDATED,
    PUBLISHED_IMMEDIATELY,
    PUBLICATION_SCHEDULED,
    SCHEDULE_CANCELLED,
    SCHEDULE_ACTIVATED,
    VISIBILITY_CHANGED,
    SELLING_STATUS_CHANGED,
    RETIRED
}
