package com.miriyum.domain.notification.dto.source;

public enum NotificationPurpose {
    RESERVATION_CONFIRMED,
    RESERVATION_CHANGED,
    RESERVATION_REJECTED,
    RESERVATION_CANCELLED,
    RESERVATION_EXPIRED,
    RESERVATION_VISIT_REMINDER,
    RESERVATION_COORDINATION_REQUIRED,
    RESERVATION_VISIT_COMPLETED,
    RESERVATION_NO_SHOW,
    PICKUP_RESERVATION_CONFIRMED,
    PICKUP_RESERVATION_CANCELLED,
    MENU_HOLD_FULFILLMENT_AT_RISK,
    MENU_SUBSTITUTION_PROPOSED,
    MENU_SUBSTITUTION_ACCEPTED,
    MENU_SUBSTITUTION_REJECTED,
    MENU_SUBSTITUTION_EXPIRED,
    WAITING_ENTRY_IMMINENT,
    WAITING_CALLED,
    WAITING_CANCELLED,
    WAITING_NO_SHOW,
    WAITING_CHECKED_IN,
    WAITING_CLOSED_BY_STORE
}
