package com.miriyum.domain.notification.dto.source;

public enum NotificationPurpose {
    RESERVATION_CONFIRMED,
    RESERVATION_CHANGED,
    RESERVATION_REJECTED,
    RESERVATION_CANCELLED,
    RESERVATION_EXPIRED,
    RESERVATION_VISIT_REMINDER,
    RESERVATION_COORDINATION_REQUIRED,
    PICKUP_RESERVATION_CONFIRMED,
    PICKUP_RESERVATION_CANCELLED,
    MENU_HOLD_FULFILLMENT_AT_RISK,
    MENU_SUBSTITUTION_PROPOSED,
    MENU_SUBSTITUTION_ACCEPTED,
    MENU_SUBSTITUTION_REJECTED,
    MENU_SUBSTITUTION_EXPIRED
}
