package com.miriyum.domain.platformoperator.enums;

/** 플랫폼 운영자 업무가 요청할 수 있는 고정 최소 권한 catalog다. */
public enum PlatformOperatorPermission {
    OPERATOR_CREATE,
    OPERATOR_AUTHORITY_MANAGE,
    OPERATOR_SUSPEND,
    ONBOARDING_REVIEW,
    ONBOARDING_EVIDENCE_READ,
    MEMBER_READ_MINIMAL,
    MEMBER_RECOVERY,
    ACCOUNT_SANCTION,
    ACCOUNT_APPEAL_REVIEW,
    STORE_READ_MINIMAL,
    STORE_SANCTION,
    OPERATIONS_MONITOR_READ,
    PAYMENT_RECOVERY_EXECUTE,
    PAYMENT_RECOVERY_HIGH_VALUE_APPROVE,
    AUDIT_READ,
    INCIDENT_RESPOND,
    BREAK_GLASS_APPROVE
}
